name: Code Quality

on:
  push:
    branches:
  pull_request:

jobs:
  ESLint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.0.0
    - name: Restore CI Cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-13-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      run: yarn
    - name: Run ESLint
      uses: discordjs/action-eslint@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        job-name: ESLint